config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'venues/show'
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
 authenticate :user, lambda { |u| u.admin? } do
   mount Sidekiq::Web => '/sidekiq'
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root 'venues#show'
  get 'search', to: 'venues#show'
end

app/models/venue.rb
# == Schema Information
#
# Table name: venues
#
#  id         :uuid             not null, primary key
#  address    :string           default(""), not null
#  country    :string           default(""), not null
#  latitude   :float            default(0.0), not null
#  longitude  :float            default(0.0), not null
#  name       :string           default(""), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Venue < ApplicationRecord
has_and_belongs_to_many :categories
geocoded_by :address
after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }


def distance location
 Geocoder::Calculations.distance_between([latitude, longitude], [location['lat'], location['lng']])
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  
    def index
      @venues = VenuesIndex.load
    end 

  def show
    if params[:term].nil?
      @venues = []
    else
      @location = address_to_geolocation params[:term]
      scope = search_by_location
      @total_count = scope.total_count
      @venues = scope.limit(10).load
    end
  end

  private

    def address_to_geolocation term
      res = Geocoder.search(term) 
      res.first.geometry['location']
    end


    def search_by_location
      VenuesIndex
        .filter {match_all}
        .filter(geo_distance: {
          distance: "2km",
          location: {lat: @location['lat'], lon: @location['lng']}
        })
        .order(_geo_distance: {
            location: {lat: @location['lat'], lon: @location['lng']}
          })
    end

end

app/views/venues/show.html.erb
<h1>Search venues</h1>
<% if @total_count %>
    <h3><%= @total_count %> venues found near <%= params[:term] %></h3>
    <%= link_to 'All venues', search_path(term: params[:term]) %> | <%= link_to 'Closest venues', search_path(term: params[:term], sort: 'distance') %>
<% end %>
<%= form_for :term, url: search_path, method: :get do |form| %>
	<p>
		Venues near
    <%= text_field_tag :term, params[:term] %>
    <%= submit_tag "Search", name: nil %>
	</p>
<% end %>
<hr/>
<div id='search-results'>
	<% @venues.each do |venue| %>
	  <div>
	    <h3><%= venue.name %></h3>
	    <% if venue.address %>
	      <p>Address: <%= venue.address %></p>
	    <% end %>
			<p>Distance: <%= number_to_human(venue.distance(@location), precision: 2, units: {unit: 'km'}) %></p>
		</div>
	<% end %>
</div>